name: Build packages

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ANACONDA_TOKEN:
        description: 'Anaconda Token'
      ANACONDA_USER:
        description: 'Anaconda User'

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  DEBIAN_FRONTEND: noninteractive
  GHA_MACHINE_TYPE: "n2-standard-4"
  APT_REQUIREMENTS: binutils build-essential csh curl git libgl1 pkg-config sudo wget

defaults:
  run:
    shell: bash

jobs:
  openroad-linux-py37:
    runs-on: [self-hosted, Linux, X64]
    container: ubuntu:20.04
    env:
      PACKAGE: "pnr/openroad"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v3
      - run: apt -qqy update && apt -qqy install ${{ env.APT_REQUIREMENTS }}
      - uses: ./ci
